# Generated by Django 4.2.3 on 2023-11-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_educationalresource_resource_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalresource',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
