# Generated by Django 4.2.6 on 2023-10-19 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationalResource",
            fields=[
                ("resource_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("content_type", models.CharField(max_length=100)),
                ("resource_url", models.CharField(max_length=200)),
                ("created_date", models.DateTimeField()),
                ("updated_date", models.DateTimeField()),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.user"
                    ),
                ),
            ],
        ),
    ]
