# Generated by Django 4.2.6 on 2023-10-19 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("campaign_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("approved", models.BooleanField()),
                (
                    "current_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("goal_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("category", models.CharField(max_length=100)),
                ("file_url", models.CharField(max_length=200)),
                ("created_date", models.DateTimeField()),
                ("updated_date", models.DateTimeField()),
                (
                    "changemaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_campaigns",
                        to="User.user",
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="led_campaigns",
                        to="User.user",
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentored_campaigns",
                        to="User.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CampaignChangemakers",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Campaign.campaign",
                    ),
                ),
                (
                    "changemaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.user"
                    ),
                ),
            ],
        ),
    ]
