# Generated by Django 4.2.3 on 2023-11-01 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('approved', models.BooleanField(null=True)),
                ('current_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('file_url', models.CharField(max_length=200, null=True)),
                ('created_date', models.DateTimeField(null=True)),
                ('updated_date', models.DateTimeField(null=True)),
                ('changemaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_campaigns', to='User.user')),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='led_campaigns', to='User.user')),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentored_campaigns', to='User.user')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignChangemakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Campaign.campaign')),
                ('changemaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
    ]
