# Generated by Django 4.2.6 on 2023-10-19 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("address_id", models.AutoField(primary_key=True, serialize=False)),
                ("country", models.CharField(max_length=100)),
                ("street_name", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="SocialMediaHandle",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "facebook_link",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "twitter_link",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "linkedin_link",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("date_of_birth", models.DateField()),
                ("qualification", models.CharField(max_length=100)),
                ("primary_phone_number", models.CharField(max_length=20)),
                ("secondary_phone_number", models.CharField(max_length=20)),
                ("user_type", models.CharField(max_length=50)),
                ("created_time", models.DateTimeField()),
                ("updated_time", models.DateTimeField()),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="User.address",
                    ),
                ),
                (
                    "social_handle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="User.socialmediahandle",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="socialmediahandle",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="User.user"
            ),
        ),
        migrations.CreateModel(
            name="LoginDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("password_hash", models.CharField(max_length=200)),
                ("salt_hash", models.CharField(max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="User.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="User.user",
            ),
        ),
    ]
